// GENERATED by scripts/qa/grant_rates_thailand.py — do not edit by hand.
// Student visa grant rates, Thai citizens, primary applicants.
// Source: Department of Home Affairs, BP0015 Student visa grant rates
// (data.gov.au dataset "student-visas"). Rate = granted / (granted + refused), %.
export const GRANT_RATE_PERIOD = { from: "2025-09", to: "2026-08" } as const;

export type AgeGroup = "15-19" | "20-24" | "25-29" | "30-34" | "35-39" | "40+";
export interface GrantRateCell { rate: number; n: number }
export interface GrantRateLocation { average: number; n: number; byAge: Record<AgeGroup, GrantRateCell> }

export const grantRates: Record<"he" | "elicos" | "vet", Record<"offshore" | "onshore", GrantRateLocation>> = {
  he: {
    offshore: { average: 94.6, n: 822, byAge: { "15-19": { rate: 97.8, n: 317 }, "20-24": { rate: 97.8, n: 269 }, "25-29": { rate: 89.5, n: 152 }, "30-34": { rate: 84.5, n: 58 }, "35-39": { rate: 88.2, n: 17 }, "40+": { rate: 55.6, n: 9 } } },
    onshore: { average: 93.4, n: 470, byAge: { "15-19": { rate: 100.0, n: 34 }, "20-24": { rate: 96.9, n: 131 }, "25-29": { rate: 94.5, n: 181 }, "30-34": { rate: 88.3, n: 103 }, "35-39": { rate: 83.3, n: 12 }, "40+": { rate: 66.7, n: 9 } } },
  },
  elicos: {
    offshore: { average: 51.7, n: 741, byAge: { "15-19": { rate: 43.8, n: 64 }, "20-24": { rate: 61.5, n: 288 }, "25-29": { rate: 49.3, n: 268 }, "30-34": { rate: 39.6, n: 96 }, "35-39": { rate: 33.3, n: 21 }, "40+": { rate: 50.0, n: 2 } } },
    onshore: { average: 87.3, n: 355, byAge: { "15-19": { rate: 100.0, n: 6 }, "20-24": { rate: 97.5, n: 80 }, "25-29": { rate: 88.4, n: 173 }, "30-34": { rate: 84.3, n: 70 }, "35-39": { rate: 64.7, n: 17 }, "40+": { rate: 33.3, n: 9 } } },
  },
  vet: {
    offshore: { average: 23.8, n: 101, byAge: { "15-19": { rate: 33.3, n: 15 }, "20-24": { rate: 27.3, n: 22 }, "25-29": { rate: 34.5, n: 29 }, "30-34": { rate: 12.0, n: 25 }, "35-39": { rate: 0.0, n: 4 }, "40+": { rate: 0.0, n: 6 } } },
    onshore: { average: 63.4, n: 2874, byAge: { "15-19": { rate: 76.2, n: 21 }, "20-24": { rate: 81.9, n: 221 }, "25-29": { rate: 72.7, n: 1227 }, "30-34": { rate: 63.7, n: 917 }, "35-39": { rate: 35.6, n: 298 }, "40+": { rate: 22.1, n: 190 } } },
  },
};
